name: Validate Compose Files
description: Validates docker-compose files using `docker compose config`
author: Kamal Gurramkonda
inputs:
  files:
    description: JSON array of docker-compose file paths to validate
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Docker CLI
      shell: bash
      run: |
        echo "Ensuring Docker CLI is installed..."
        docker --version
        docker compose version

    - name: Validate Compose Files
      shell: bash
      run: |
        set -e
        # Decode JSON into bash array
        files=$(echo '${{ inputs.files }}' | jq -r '.[]')

        if [[ -z "${files[@]}" ]]; then
          echo "❌ No docker compose files provided."
          exit 1
        fi

        echo "Files: $files"

        exit_code=0
        echo "$files" | while read -r file; do
          echo "🔍 Validating: $file"
          if docker compose -f "$file" config > /dev/null; then
            echo "✅ Valid: $file"
          else
            echo "❌ Invalid: $file"
            exit_code=1
          fi
        done

        exit $exit_code
