name: Validate Compose Files
description: Validates docker-compose files using `docker compose config`
author: Kamal Gurramkonda
inputs:
  patterns:
    description: Glob patterns for compose files to validate
    required: false
    default: |
      **/docker-compose.yml
      **/docker-compose.*.yml
      **/docker-compose-*.yml
      **/docker-compose.yaml
      **/docker-compose.*.yaml
      **/docker-compose-*.yaml

runs:
  using: "composite"
  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        echo "Ensuring Docker CLI is installed..."
        docker --version
        docker compose version

    - name: Validate Compose Files
      shell: bash
      run: |
        shopt -s globstar nullglob

        echo "Searching for docker-compose files..."

        IFS=$'\n' read -rd '' -a patterns <<< "${{ inputs.patterns }}"

        # Read patterns and expand them
        files=()
        for pattern in "${patterns[@]}"; do
            for file in $pattern; do
            files+=("$file")
            done
        done
        echo Found docker files: "${files[@]}"

        if [[ ${#files[@]} -eq 0 ]]; then
            echo "❌ No compose files found matching the patterns."
            exit 1
        fi

        exit_code=0
        for file in "${files[@]}"; do
            echo "🔍 Validating: $file"
            if docker compose -f "$file" config > /dev/null; then
                echo "✅ Valid: $file"
            else
                echo "❌ Invalid: $file"
                exit_code=1
            fi
        done
        exit $exit_code
