name: Assign PR Users
description: Assigns a pull request to one or more users
inputs:
  assignees:
    description: Comma-separated list of GitHub usernames
    required: true

runs:
  using: "composite"
  steps:
    - name: Assign PR to ${{ inputs.assignees }}
      uses: actions/github-script@v7
      with:
        script: |
          const assignees = '${{ inputs.assignees }}'.split(',').map(a => a.trim()).filter(Boolean);
          github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            assignees: assignees
          });
